// server.js
const express = require('express');
const path = require('path');
const app = express();

// Get the absolute paths
const clientPkgPath = path.resolve(__dirname, '../pkg');
const staticPath = path.resolve(__dirname, './static');

// Serve static files
app.use(express.static(staticPath));

// serves the WebAssembly files that are generated by wasm-pack
// This is crucial, since in static/index.html we are importing the wasm module
// ```const module = await import('../../pkg/wasm_client.js');```
app.use('/pkg', express.static(clientPkgPath));

// Log the paths we're serving (helpful for debugging)
console.log('Serving current directory:', staticPath);
console.log('Serving pkg directory:', clientPkgPath);

app.listen(3000, () => {
    console.log('Server running at http://localhost:3000');
});
